### ISSUE TITLE
The script won't input the commands into Remote Play

### ISSUE THREAD

**Issue by Haycobbe** [septomor/FF9-Jump-Rope-Script#9]
Let me first thank you for creating this. I am eternally grateful. After much work I have gotten the script to run properly, I can tell it's running because it does input the "Enter" command into notepad and other programs. It will not however input the command into Remote Play no matter what I try. I have tried older versions of remote play. I cannot figure it out please help me.

**Comment by Haycobbe** [comment]
Figured it out. Had to run the script as Admin. Which I had problems doing because I had issues getting the script to run in the first place due to it not finding Autohotkey.exe. I fixed it by naming the script itself Autohotkey.ahk then renaming AutohotkeyU64.exe to just Autohotkey.exe. If the script is the same name as the autohotkey program it will run the script when you open the program. So I then just ran Autohotkey.exe as admin while having the jump script of the same name in the same folder. Worked on the third try with 690 latency. Thank you for your hard working creating this script. God bless.

**Comment by Sieglinde-V** [comment]
I've tried what you've said, however I didn't see something precisely called "AutohotkeyU64.exe" so did my best to figure out which one you meant. No matter which one I do try, I get an error stating this 

Error: Function calls require a space or "(".  Use comma only between parameters.

Text:	DetectHiddenWindows, On
Line:	1
File:	C:\Program Files\AutoHotkey\v2\Autohotkey.ahk

The program will exit.

I'm not very computer savvy but if someone would be willing to help, I'd appreciate it. This happens when I try running in administrator mode since I can get the script running, but have the same exact issues Haycobbe had in his first message where nothing happens. The script I copied is exactly what's there and I've checked many times.

**Comment by Haycobbe** [comment]
Try using the older version of autohotkey. V1

**Comment by Haycobbe** [comment]
Also, I tried getting another script to work using PS shareplay and couldn't because I think the new version doesn't allow for keyboard inputs unless the game natively supports it. I think they patched it out. And when I tried to install the older version of shareplay it wouldn't let me... kept saying it wasnt a valid windows install or something. Good luck.

**Comment by Sieglinde-V** [comment]
Unfortunately, I was not able to get it to work. I used an older version of AutoHotKey and found the file you specified, followed the directions precisely but it wouldn't work. The inputs would still not be registered by PS remote play. Older versions of remote play seem to have issues with everyone when installing. The oldest I was able to get was 5.5 and it does not work. I suppose the last issues is figuring out a way to install 5.0 of Remote Play.
